# Generated by Django 5.2.17 on 2026-09-09 04:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_opening_post", models.BooleanField(default=False)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("body", models.TextField(blank=True, max_length=4000)),
                ("display_name", models.CharField(blank=True, max_length=64)),
                ("tripcode", models.CharField(blank=True, max_length=16)),
                ("sage", models.BooleanField(default=False)),
                (
                    "deletion_password_hash",
                    models.CharField(blank=True, max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_tombstone", models.BooleanField(default=False)),
                (
                    "tombstone_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USER", "Deleted by user"),
                            ("MODERATOR", "Deleted by moderator"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("ip_removed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["id"],
                "permissions": [
                    ("delete_thread", "Can delete a thread"),
                    ("lock_thread", "Can lock/unlock a thread"),
                    ("sticky_thread", "Can sticky/unsticky a thread"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("IMAGE", "Image"), ("VIDEO", "Video")], max_length=8
                    ),
                ),
                ("mime_type", models.CharField(max_length=32)),
                ("file", models.FileField(upload_to="images/")),
                ("thumbnail", models.FileField(blank=True, upload_to="thumbs/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size_bytes", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="posts.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bumped_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("locked", models.BooleanField(default=False)),
                ("stickied", models.BooleanField(default=False)),
                ("stickied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="boards.board",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.thread",
            ),
        ),
        migrations.CreateModel(
            name="PostReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references_made",
                        to="posts.post",
                    ),
                ),
                (
                    "target_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referenced_by",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_post"], name="posts_postr_target__c52804_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_post", "target_post"),
                        name="posts_reference_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["board", "bumped_at"], name="posts_threa_board_i_214de8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["board", "stickied", "stickied_at"],
                name="posts_threa_board_i_702194_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["thread", "id"], name="posts_post_thread__9c8daf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="posts_post_ip_addr_c2cf22_idx",
            ),
        ),
    ]
