# Generated by Django 5.2.17 on 2026-09-09 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=128)),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["scope", "key", "window_start"],
                        name="antispam_ra_scope_649fa4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "key", "window_start"),
                        name="antispam_ratelimit_unique_window",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProofOfWorkChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("THREAD", "Thread creation"),
                            ("REPLY", "Reply"),
                            ("REPORT", "Report"),
                        ],
                        max_length=16,
                    ),
                ),
                ("challenge", models.CharField(max_length=64)),
                ("difficulty_bits", models.PositiveSmallIntegerField()),
                ("client_ip", models.GenericIPAddressField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pow_challenges",
                        to="boards.board",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["board", "action", "expires_at"],
                        name="antispam_pr_board_i_406ad4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="antispam_pr_expires_90d67f_idx"
                    ),
                ],
            },
        ),
    ]
