/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all boards */
        get: operations["listBoards"];
        put?: never;
        /** Create a board */
        post: operations["createBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a board by slug */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boards/{slug}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threads on a board (catalog) */
        get: operations["listThreads"];
        put?: never;
        /** Create a thread (and its OP post) on a board */
        post: operations["createThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a thread with its posts */
        get: operations["getThread"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reply to a thread */
        post: operations["createReply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single post by id */
        get: operations["getPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Board: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            description: string;
            nsfw: boolean;
            thread_limit: number;
            bump_limit: number;
            /** Format: date-time */
            created_at: string;
        };
        CreateBoard: {
            slug: string;
            name: string;
            description?: string;
            nsfw?: boolean;
        };
        Thread: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            board_id: number;
            subject: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            bumped_at: string;
            is_pinned: boolean;
            is_locked: boolean;
            is_archived: boolean;
        };
        CreateThread: {
            subject?: string;
            body: string;
            /** @description `Name#password` derives a tripcode; a bare name does not. */
            author_name?: string;
        };
        ThreadWithPosts: components["schemas"]["Thread"] & {
            posts: components["schemas"]["Post"][];
        };
        Post: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            thread_id: number;
            /** Format: int64 */
            board_id: number;
            /** Format: int64 */
            parent_id: number | null;
            body: string;
            author_name: string;
            tripcode: string | null;
            /** Format: date-time */
            created_at: string;
            is_deleted: boolean;
        };
        CreatePost: {
            body: string;
            author_name?: string;
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        BoardSlug: string;
        ThreadId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listBoards: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"][];
                };
            };
        };
    };
    createBoard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoard"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["BoardSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Board"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listThreads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["BoardSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Thread"][];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["BoardSlug"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThread"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadWithPosts"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getThread: {
        parameters: {
            query?: {
                /** @description Only return posts with id greater than this (for polling). */
                since?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadWithPosts"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    createReply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePost"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
