//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "boards")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub nsfw: bool,
    pub thread_limit: i64,
    pub bump_limit: i64,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::bans::Entity")]
    Bans,
    #[sea_orm(has_many = "super::mod_actions::Entity")]
    ModActions,
    #[sea_orm(has_many = "super::mod_board_acl::Entity")]
    ModBoardAcl,
    #[sea_orm(has_many = "super::posts::Entity")]
    Posts,
    #[sea_orm(has_many = "super::threads::Entity")]
    Threads,
}

impl Related<super::bans::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bans.def()
    }
}

impl Related<super::mod_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModActions.def()
    }
}

impl Related<super::mod_board_acl::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModBoardAcl.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl Related<super::threads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Threads.def()
    }
}

impl Related<super::mod_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        super::mod_board_acl::Relation::ModAccounts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::mod_board_acl::Relation::Boards.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
