//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod bans;
pub mod boards;
pub mod files;
pub mod mod_accounts;
pub mod mod_actions;
pub mod mod_board_acl;
pub mod posts;
pub mod puzzle_challenges;
pub mod reports;
pub mod threads;
