//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mod_accounts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::mod_actions::Entity")]
    ModActions,
    #[sea_orm(has_many = "super::mod_board_acl::Entity")]
    ModBoardAcl,
}

impl Related<super::mod_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModActions.def()
    }
}

impl Related<super::mod_board_acl::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModBoardAcl.def()
    }
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        super::mod_board_acl::Relation::Boards.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::mod_board_acl::Relation::ModAccounts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
