//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mod_board_acl")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub mod_account_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub board_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Boards,
    #[sea_orm(
        belongs_to = "super::mod_accounts::Entity",
        from = "Column::ModAccountId",
        to = "super::mod_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ModAccounts,
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl Related<super::mod_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModAccounts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
