//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "mod_actions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub mod_account_id: i64,
    #[sea_orm(column_type = "Text")]
    pub action: String,
    pub target_post_id: Option<i64>,
    pub board_id: Option<i64>,
    #[sea_orm(column_type = "Text")]
    pub created_at: String,
    #[sea_orm(column_type = "Text")]
    pub note: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::boards::Entity",
        from = "Column::BoardId",
        to = "super::boards::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Boards,
    #[sea_orm(
        belongs_to = "super::mod_accounts::Entity",
        from = "Column::ModAccountId",
        to = "super::mod_accounts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ModAccounts,
    #[sea_orm(
        belongs_to = "super::posts::Entity",
        from = "Column::TargetPostId",
        to = "super::posts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Posts,
}

impl Related<super::boards::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Boards.def()
    }
}

impl Related<super::mod_accounts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ModAccounts.def()
    }
}

impl Related<super::posts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Posts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
