//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::bans::Entity as Bans;
pub use super::boards::Entity as Boards;
pub use super::files::Entity as Files;
pub use super::mod_accounts::Entity as ModAccounts;
pub use super::mod_actions::Entity as ModActions;
pub use super::mod_board_acl::Entity as ModBoardAcl;
pub use super::posts::Entity as Posts;
pub use super::puzzle_challenges::Entity as PuzzleChallenges;
pub use super::reports::Entity as Reports;
pub use super::threads::Entity as Threads;
