# Generated by Django 5.2.17 on 2026-09-09 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        max_length=16,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Board code must be lowercase letters/digits, 1-16 characters.",
                                regex="^[a-z0-9]{1,16}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.CharField(blank=True, max_length=256)),
                ("enabled", models.BooleanField(default=True)),
                ("max_active_threads", models.PositiveIntegerField(default=100)),
                ("threads_per_page", models.PositiveIntegerField(default=15)),
                ("preview_reply_count", models.PositiveIntegerField(default=3)),
                ("max_media_per_thread", models.PositiveIntegerField(default=150)),
                ("max_post_length", models.PositiveIntegerField(default=2000)),
                ("max_image_bytes", models.PositiveIntegerField(default=10485760)),
                ("max_webm_bytes", models.PositiveIntegerField(default=52428800)),
                ("allow_jpeg", models.BooleanField(default=True)),
                ("allow_png", models.BooleanField(default=True)),
                ("allow_webp", models.BooleanField(default=True)),
                ("allow_gif", models.BooleanField(default=True)),
                ("allow_webm", models.BooleanField(default=True)),
                ("bump_limit", models.PositiveIntegerField(default=300)),
                ("new_threads_enabled", models.BooleanField(default=True)),
                ("tripcodes_enabled", models.BooleanField(default=True)),
                ("motd", models.TextField(blank=True)),
                ("thread_rate_limit_count", models.PositiveIntegerField(default=3)),
                (
                    "thread_rate_limit_window_seconds",
                    models.PositiveIntegerField(default=600),
                ),
                ("reply_rate_limit_count", models.PositiveIntegerField(default=10)),
                (
                    "reply_rate_limit_window_seconds",
                    models.PositiveIntegerField(default=300),
                ),
                ("report_rate_limit_count", models.PositiveIntegerField(default=5)),
                (
                    "report_rate_limit_window_seconds",
                    models.PositiveIntegerField(default=600),
                ),
                (
                    "report_duplicate_window_seconds",
                    models.PositiveIntegerField(default=3600),
                ),
                ("report_requires_pow", models.BooleanField(default=False)),
                (
                    "pow_difficulty_report_bits",
                    models.PositiveSmallIntegerField(default=12),
                ),
                (
                    "pow_difficulty_thread_bits",
                    models.PositiveSmallIntegerField(default=18),
                ),
                (
                    "pow_difficulty_reply_bits",
                    models.PositiveSmallIntegerField(default=14),
                ),
                ("pow_challenge_ttl_seconds", models.PositiveIntegerField(default=600)),
                (
                    "deletion_password_attempts_per_window",
                    models.PositiveIntegerField(default=5),
                ),
                (
                    "deletion_password_window_seconds",
                    models.PositiveIntegerField(default=600),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("global_motd", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site configuration",
                "verbose_name_plural": "Site configuration",
            },
        ),
    ]
